/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type Credits = {
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  locations?: Array<{
    name?: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    groups?: Array<{
      name?: string;
      description?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      items?: Array<{
        role?: string;
        people?: string;
        _type: "creditItem";
        _key: string;
      }>;
      _type: "creditGroup";
      _key: string;
    }>;
    _type: "creditLocation";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ProgramReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "program";
};

export type ArtistReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "artist";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  program: ProgramReference;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  dateTimes?: Array<{
    start: string;
    end: string;
    _type: "dateTimeRange";
    _key: string;
  }>;
  timezoneLabel?: string;
  cost?: string;
  locationShort?: string;
  location?: string;
  accessInfo?: string;
  links?: Array<{
    label: string;
    shortLabel?: string;
    url: string;
    _key: string;
  }>;
  featuredArtists?: Array<{
    artist?: ArtistReference;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    name?: string;
    bio?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "featuredArtist";
    _key: string;
  }>;
  artworks?: Array<{
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      credits?: string;
      _type: "image";
    };
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "artwork";
    _key: string;
  }>;
  aboutProgram?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  schedule?: {
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    items?: Array<{
      title: string;
      time?: string;
      description?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      _type: "scheduleItem";
      _key: string;
    }>;
  };
  credits?: Credits;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ArtAndTechnologyPage = {
  _id: string;
  _type: "artAndTechnologyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  introText?: string;
  featuredPrograms?: Array<
    {
      _key: string;
    } & ProgramReference
  >;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  projectStatement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  links?: Array<{
    label: string;
    shortLabel?: string;
    url: string;
    _key: string;
  }>;
  programs?: Array<{
    program: ProgramReference;
    yearStart: number;
    yearEnd: number;
    location?: string;
    _type: "programMembership";
    _key: string;
  }>;
  program: ProgramReference;
  locations: Array<string>;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  people?: string;
  date: string;
  endDate?: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  locations: Array<string>;
  program: ProgramReference;
  pressLinks?: Array<{
    label: string;
    shortLabel?: string;
    url: string;
    _key: string;
  }>;
  content?: Array<
    | {
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        _type: "singleImage";
        _key: string;
      }
    | {
        image1: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        image2: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        _type: "twoImages";
        _key: string;
      }
    | {
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        text?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "normal"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "imageAndText";
        _key: string;
      }
    | {
        text?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "normal"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        _type: "textAndImage";
        _key: string;
      }
  >;
  credits?: Credits;
  related?: ArrayOf<ArtistReference | ProjectReference>;
};

export type Program = {
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  displayTitle?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug: Slug;
  shortLabel: string;
  description: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  accentColor: string;
  thumbnails: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "thumbnail";
    _key: string;
  }>;
  pageDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  jumpToButtons?: Array<{
    label: string;
    anchor?: string;
    _type: "jumpToButton";
    _key: string;
  }>;
  openCallTitle?: string;
  openCallImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  openCallTimeline?: string;
  openCallWhere?: string;
  openCallBenefits?: string;
  openCallDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  locationContent?: Array<{
    location: string;
    displayTitle: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    accentColor?: string;
    _type: "locationTab";
    _key: string;
  }>;
  featuredArtists?: Array<
    {
      _key: string;
    } & ArtistReference
  >;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Credits
  | SanityImageAssetReference
  | ProgramReference
  | ArtistReference
  | Event
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ArtAndTechnologyPage
  | ProjectReference
  | Artist
  | Project
  | Program
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../client/src/sanity/queries.ts
// Variable: getArtistsBySlugQuery
// Query: *[_type == "artist" && slug.current == $slug]{    ...,    "program": programs[0].program->{ _id, title, slug, shortLabel },    projects[]->{      ...    }  }[0]
export type GetArtistsBySlugQueryResult = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  projectStatement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  links?: Array<{
    label: string;
    shortLabel?: string;
    url: string;
    _key: string;
  }>;
  programs?: Array<{
    program: ProgramReference;
    yearStart: number;
    yearEnd: number;
    location?: string;
    _type: "programMembership";
    _key: string;
  }>;
  program: {
    _id: string;
    title: string;
    slug: Slug;
    shortLabel: string;
  } | null;
  locations: Array<string>;
  projects: Array<{
    _id: string;
    _type: "project";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    people?: string;
    date: string;
    endDate?: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      credits?: string;
      _type: "image";
    };
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    locations: Array<string>;
    program: ProgramReference;
    pressLinks?: Array<{
      label: string;
      shortLabel?: string;
      url: string;
      _key: string;
    }>;
    content?: Array<
      | {
          image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            credits?: string;
            _type: "image";
          };
          text?: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h1"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }>;
          _type: "imageAndText";
          _key: string;
        }
      | {
          image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            credits?: string;
            _type: "image";
          };
          _type: "singleImage";
          _key: string;
        }
      | {
          text?: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?:
              | "blockquote"
              | "h1"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "normal";
            listItem?: "bullet" | "number";
            markDefs?: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }>;
            level?: number;
            _type: "block";
            _key: string;
          }>;
          image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            credits?: string;
            _type: "image";
          };
          _type: "textAndImage";
          _key: string;
        }
      | {
          image1: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            credits?: string;
            _type: "image";
          };
          image2: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            credits?: string;
            _type: "image";
          };
          _type: "twoImages";
          _key: string;
        }
    >;
    credits?: Credits;
    related?: ArrayOf<ArtistReference | ProjectReference>;
  }> | null;
} | null;

// Source: ../client/src/sanity/queries.ts
// Variable: getProjectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0]{      ...,      "program": program->{ _id, title, slug, shortLabel, displayTitle },      related[]->{        _id,        _type,        "slug": slug.current,        "image": select(          _type == "project" => heroImage,          _type == "artist" => image,        ),        "title": select(          _type == "project" => title,          _type == "artist" => name,        ),      },    }
export type GetProjectBySlugQueryResult = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  people?: string;
  date: string;
  endDate?: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  locations: Array<string>;
  program: {
    _id: string;
    title: string;
    slug: Slug;
    shortLabel: string;
    displayTitle: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  };
  pressLinks?: Array<{
    label: string;
    shortLabel?: string;
    url: string;
    _key: string;
  }>;
  content?: Array<
    | {
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        text?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "imageAndText";
        _key: string;
      }
    | {
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        _type: "singleImage";
        _key: string;
      }
    | {
        text?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        _type: "textAndImage";
        _key: string;
      }
    | {
        image1: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        image2: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        _type: "twoImages";
        _key: string;
      }
  >;
  credits?: Credits;
  related: Array<
    | {
        _id: string;
        _type: "artist";
        slug: string;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        title: string;
      }
    | {
        _id: string;
        _type: "project";
        slug: string;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        };
        title: string;
      }
  > | null;
} | null;

// Source: ../client/src/sanity/queries.ts
// Variable: getArtAndTechnologyPageQuery
// Query: *[_type == "artAndTechnologyPage"][0]{      heading,      introText,      featuredPrograms[]->{        ...      }    }
export type GetArtAndTechnologyPageQueryResult = {
  heading: string | null;
  introText: string | null;
  featuredPrograms: Array<{
    _id: string;
    _type: "program";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    displayTitle?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    slug: Slug;
    shortLabel: string;
    description: string;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      credits?: string;
      _type: "image";
    };
    accentColor: string;
    thumbnails: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      credits?: string;
      _type: "thumbnail";
      _key: string;
    }>;
    pageDescription?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    jumpToButtons?: Array<{
      label: string;
      anchor?: string;
      _type: "jumpToButton";
      _key: string;
    }>;
    openCallTitle?: string;
    openCallImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      credits?: string;
      _type: "image";
    };
    openCallTimeline?: string;
    openCallWhere?: string;
    openCallBenefits?: string;
    openCallDescription?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    locationContent?: Array<{
      location: string;
      displayTitle: string;
      description?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      accentColor?: string;
      _type: "locationTab";
      _key: string;
    }>;
    featuredArtists?: Array<
      {
        _key: string;
      } & ArtistReference
    >;
    featuredProjects?: Array<
      {
        _key: string;
      } & ProjectReference
    >;
  }> | null;
} | null;

// Source: ../client/src/sanity/queries.ts
// Variable: getProgramsQuery
// Query: *[_type == "program"]{    ...  }
export type GetProgramsQueryResult = Array<{
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  displayTitle?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug: Slug;
  shortLabel: string;
  description: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  accentColor: string;
  thumbnails: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "thumbnail";
    _key: string;
  }>;
  pageDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  jumpToButtons?: Array<{
    label: string;
    anchor?: string;
    _type: "jumpToButton";
    _key: string;
  }>;
  openCallTitle?: string;
  openCallImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  openCallTimeline?: string;
  openCallWhere?: string;
  openCallBenefits?: string;
  openCallDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  locationContent?: Array<{
    location: string;
    displayTitle: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    accentColor?: string;
    _type: "locationTab";
    _key: string;
  }>;
  featuredArtists?: Array<
    {
      _key: string;
    } & ArtistReference
  >;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
}>;

// Source: ../client/src/sanity/queries.ts
// Variable: getProgramBySlugQuery
// Query: *[_type == "program" && slug.current == $slug][0]{        _id, title, displayTitle, slug, shortLabel, accentColor,        heroImage {          asset->{_id, url},          alt, credits        },        pageDescription,        jumpToButtons,        openCallTitle,        openCallImage {          asset->{_id, url},          alt, credits        },        openCallTimeline,        openCallWhere,        openCallBenefits,        openCallDescription,        locationContent[]{          _key,          location, displayTitle, description,          accentColor        },        featuredArtists[]->{          _id, name, slug,          image {            asset->{_id, url},            alt          }        },        featuredProjects[]->{          _id, title, slug,          heroImage {            asset,            alt          },          people        }      }
export type GetProgramBySlugQueryResult = {
  _id: string;
  title: string;
  displayTitle: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: Slug;
  shortLabel: string;
  accentColor: string;
  heroImage: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string;
    credits: string | null;
  };
  pageDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  jumpToButtons: Array<{
    label: string;
    anchor?: string;
    _type: "jumpToButton";
    _key: string;
  }> | null;
  openCallTitle: string | null;
  openCallImage: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string;
    credits: string | null;
  };
  openCallTimeline: string | null;
  openCallWhere: string | null;
  openCallBenefits: string | null;
  openCallDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  locationContent: Array<{
    _key: string;
    location: string;
    displayTitle: string;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    accentColor: string | null;
  }> | null;
  featuredArtists: Array<{
    _id: string;
    name: string;
    slug: Slug;
    image: {
      asset: {
        _id: string;
        url: string;
      } | null;
      alt: string;
    };
  }> | null;
  featuredProjects: Array<{
    _id: string;
    title: string;
    slug: Slug;
    heroImage: {
      asset: SanityImageAssetReference | null;
      alt: string;
    };
    people: string | null;
  }> | null;
} | null;

// Source: ../client/src/sanity/queries.ts
// Variable: getResidentArtistsQuery
// Query: *[_type == "artist" && $programId in programs[].program._ref]{      _id, name, slug,      image {        asset->{_id, url},        alt      },      locations,      "membership": programs[program._ref == $programId][0]{        yearStart, yearEnd, location      }    } | order(membership.yearStart desc)
export type GetResidentArtistsQueryResult = Array<{
  _id: string;
  name: string;
  slug: Slug;
  image: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string;
  };
  locations: Array<string>;
  membership: {
    yearStart: number;
    yearEnd: number;
    location: string | null;
  } | null;
}>;

// Source: ../client/src/sanity/queries.ts
// Variable: getArtistLocationOptionsQuery
// Query: array::unique(*[_type == "artist"].locations[])
export type GetArtistLocationOptionsQueryResult = Array<string>;

// Source: ../client/src/sanity/queries.ts
// Variable: getArtistsQuery
// Query: *[    _type == "artist"    && defined(slug.current)  ][0...12]
export type GetArtistsQueryResult = Array<{
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  projectStatement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  links?: Array<{
    label: string;
    shortLabel?: string;
    url: string;
    _key: string;
  }>;
  programs?: Array<{
    program: ProgramReference;
    yearStart: number;
    yearEnd: number;
    location?: string;
    _type: "programMembership";
    _key: string;
  }>;
  program: ProgramReference;
  locations: Array<string>;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
}>;

// Source: ../client/src/sanity/queries.ts
// Variable: getArtistsByLocationsQuery
// Query: *[    _type == "artist"    && count(locations[@ in $locations]) > 0    && defined(slug.current)  ][0...12]
export type GetArtistsByLocationsQueryResult = Array<{
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  projectStatement?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  links?: Array<{
    label: string;
    shortLabel?: string;
    url: string;
    _key: string;
  }>;
  programs?: Array<{
    program: ProgramReference;
    yearStart: number;
    yearEnd: number;
    location?: string;
    _type: "programMembership";
    _key: string;
  }>;
  program: ProgramReference;
  locations: Array<string>;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
}>;

// Source: ../client/src/sanity/queries.ts
// Variable: getProjectFilterOptionsQuery
// Query: {    "programs": *[_type == "program"]{ _id, title, slug, shortLabel, accentColor, displayTitle },    "places": array::unique(*[_type == "project" && defined(slug.current)].locations[]) | order(@ asc),    "dates": array::unique(*[_type == "project" && defined(slug.current)].date) | order(@ desc)  }
export type GetProjectFilterOptionsQueryResult = {
  programs: Array<{
    _id: string;
    title: string;
    slug: Slug;
    shortLabel: string;
    accentColor: string;
    displayTitle: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }>;
  places: Array<string>;
  dates: Array<string>;
};

// Source: ../client/src/sanity/queries.ts
// Variable: getProjectsQuery
// Query: {    "projects": *[_type == "project" && defined(slug.current)      && ($program == "" || program->slug.current == $program)      && ($place == "" || $place in locations)      && ($year == "" || (  (defined(endDate) && endDate >= $yearStart && date < $yearEnd)  || (!defined(endDate) && date >= $yearStart && date < $yearEnd)))    ] | order(date desc) [$offset...$end]    {  _id,  title,  slug,  date,  endDate,  locations,  people,  "program": program->{ _id, title, slug, shortLabel, accentColor, displayTitle },  heroImage {    asset,    hotspot,    crop,    alt  },  "artists": *[_type == "artist" && references(^._id)]{ _id, name }},    "total": count(*[_type == "project" && defined(slug.current)      && ($program == "" || program->slug.current == $program)      && ($place == "" || $place in locations)      && ($year == "" || (  (defined(endDate) && endDate >= $yearStart && date < $yearEnd)  || (!defined(endDate) && date >= $yearStart && date < $yearEnd)))    ])  }
export type GetProjectsQueryResult = {
  projects: Array<{
    _id: string;
    title: string;
    slug: Slug;
    date: string;
    endDate: string | null;
    locations: Array<string>;
    people: string | null;
    program: {
      _id: string;
      title: string;
      slug: Slug;
      shortLabel: string;
      accentColor: string;
      displayTitle: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
    };
    heroImage: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    };
    artists: Array<{
      _id: string;
      name: string;
    }>;
  }>;
  total: number;
};

// Source: ../client/src/sanity/queries.ts
// Variable: getProjectFacetsQuery
// Query: {    "programSlugs": array::unique(*[_type == "project" && defined(slug.current)      && ($place == "" || $place in locations)      && ($year == "" || (  (defined(endDate) && endDate >= $yearStart && date < $yearEnd)  || (!defined(endDate) && date >= $yearStart && date < $yearEnd)))    ].program->slug.current)[@ != null],    "places": array::unique(*[_type == "project" && defined(slug.current)      && ($program == "" || program->slug.current == $program)      && ($year == "" || (  (defined(endDate) && endDate >= $yearStart && date < $yearEnd)  || (!defined(endDate) && date >= $yearStart && date < $yearEnd)))    ].locations[]) | order(@ asc),    "dates": array::unique(*[_type == "project" && defined(slug.current)      && ($program == "" || program->slug.current == $program)      && ($place == "" || $place in locations)    ].date) | order(@ desc)  }
export type GetProjectFacetsQueryResult = {
  programSlugs: Array<string>;
  places: Array<string>;
  dates: Array<string>;
};

// Source: ../client/src/sanity/queries.ts
// Variable: getEventBySlugQuery
// Query: *[_type == "event" && slug.current == $slug][0]{      ...,      "program": program->{        _id, title, slug, shortLabel, displayTitle, accentColor      },      featuredArtists[]{        _key,        artist->{ _id, name, slug },        "image": coalesce(image, artist->image),        "name": coalesce(name, artist->name),        "bio": coalesce(bio, artist->bio)      }    }
export type GetEventBySlugQueryResult = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    credits?: string;
    _type: "image";
  };
  program: {
    _id: string;
    title: string;
    slug: Slug;
    shortLabel: string;
    displayTitle: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    accentColor: string;
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  dateTimes?: Array<{
    start: string;
    end: string;
    _type: "dateTimeRange";
    _key: string;
  }>;
  timezoneLabel?: string;
  cost?: string;
  locationShort?: string;
  location?: string;
  accessInfo?: string;
  links?: Array<{
    label: string;
    shortLabel?: string;
    url: string;
    _key: string;
  }>;
  featuredArtists: Array<{
    _key: string;
    artist: {
      _id: string;
      name: string;
      slug: Slug;
    } | null;
    image:
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          credits?: string;
          _type: "image";
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        }
      | null;
    name: string | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  artworks?: Array<{
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      credits?: string;
      _type: "image";
    };
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "artwork";
    _key: string;
  }>;
  aboutProgram?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  schedule?: {
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    items?: Array<{
      title: string;
      time?: string;
      description?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      _type: "scheduleItem";
      _key: string;
    }>;
  };
  credits?: Credits;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "artist" && slug.current == $slug]{\n    ...,\n    "program": programs[0].program->{ _id, title, slug, shortLabel },\n    projects[]->{\n      ...\n    }\n  }[0]': GetArtistsBySlugQueryResult;
    '*[_type == "project" && slug.current == $slug][0]{\n      ...,\n      "program": program->{ _id, title, slug, shortLabel, displayTitle },\n      related[]->{\n        _id,\n        _type,\n        "slug": slug.current,\n        "image": select(\n          _type == "project" => heroImage,\n          _type == "artist" => image,\n        ),\n        "title": select(\n          _type == "project" => title,\n          _type == "artist" => name,\n        ),\n      },\n    }': GetProjectBySlugQueryResult;
    '*[_type == "artAndTechnologyPage"][0]{\n      heading,\n      introText,\n      featuredPrograms[]->{\n        ...\n      }\n    }': GetArtAndTechnologyPageQueryResult;
    '*[_type == "program"]{\n    ...\n  }': GetProgramsQueryResult;
    '*[_type == "program" && slug.current == $slug][0]{\n        _id, title, displayTitle, slug, shortLabel, accentColor,\n        heroImage {\n          asset->{_id, url},\n          alt, credits\n        },\n        pageDescription,\n        jumpToButtons,\n        openCallTitle,\n        openCallImage {\n          asset->{_id, url},\n          alt, credits\n        },\n        openCallTimeline,\n        openCallWhere,\n        openCallBenefits,\n        openCallDescription,\n        locationContent[]{\n          _key,\n          location, displayTitle, description,\n          accentColor\n        },\n        featuredArtists[]->{\n          _id, name, slug,\n          image {\n            asset->{_id, url},\n            alt\n          }\n        },\n        featuredProjects[]->{\n          _id, title, slug,\n          heroImage {\n            asset,\n            alt\n          },\n          people\n        }\n      }': GetProgramBySlugQueryResult;
    '*[_type == "artist" && $programId in programs[].program._ref]{\n      _id, name, slug,\n      image {\n        asset->{_id, url},\n        alt\n      },\n      locations,\n      "membership": programs[program._ref == $programId][0]{\n        yearStart, yearEnd, location\n      }\n    } | order(membership.yearStart desc)': GetResidentArtistsQueryResult;
    'array::unique(*[_type == "artist"].locations[])': GetArtistLocationOptionsQueryResult;
    '*[\n    _type == "artist"\n    && defined(slug.current)\n  ][0...12]': GetArtistsQueryResult;
    '*[\n    _type == "artist"\n    && count(locations[@ in $locations]) > 0\n    && defined(slug.current)\n  ][0...12]': GetArtistsByLocationsQueryResult;
    '{\n    "programs": *[_type == "program"]{ _id, title, slug, shortLabel, accentColor, displayTitle },\n    "places": array::unique(*[_type == "project" && defined(slug.current)].locations[]) | order(@ asc),\n    "dates": array::unique(*[_type == "project" && defined(slug.current)].date) | order(@ desc)\n  }': GetProjectFilterOptionsQueryResult;
    '{\n    "projects": *[_type == "project" && defined(slug.current)\n      && ($program == "" || program->slug.current == $program)\n      && ($place == "" || $place in locations)\n      && ($year == "" || (\n  (defined(endDate) && endDate >= $yearStart && date < $yearEnd)\n  || (!defined(endDate) && date >= $yearStart && date < $yearEnd)\n))\n    ] | order(date desc) [$offset...$end]\n    {\n  _id,\n  title,\n  slug,\n  date,\n  endDate,\n  locations,\n  people,\n  "program": program->{ _id, title, slug, shortLabel, accentColor, displayTitle },\n  heroImage {\n    asset,\n    hotspot,\n    crop,\n    alt\n  },\n  "artists": *[_type == "artist" && references(^._id)]{ _id, name }\n},\n    "total": count(*[_type == "project" && defined(slug.current)\n      && ($program == "" || program->slug.current == $program)\n      && ($place == "" || $place in locations)\n      && ($year == "" || (\n  (defined(endDate) && endDate >= $yearStart && date < $yearEnd)\n  || (!defined(endDate) && date >= $yearStart && date < $yearEnd)\n))\n    ])\n  }': GetProjectsQueryResult;
    '{\n    "programSlugs": array::unique(*[_type == "project" && defined(slug.current)\n      && ($place == "" || $place in locations)\n      && ($year == "" || (\n  (defined(endDate) && endDate >= $yearStart && date < $yearEnd)\n  || (!defined(endDate) && date >= $yearStart && date < $yearEnd)\n))\n    ].program->slug.current)[@ != null],\n    "places": array::unique(*[_type == "project" && defined(slug.current)\n      && ($program == "" || program->slug.current == $program)\n      && ($year == "" || (\n  (defined(endDate) && endDate >= $yearStart && date < $yearEnd)\n  || (!defined(endDate) && date >= $yearStart && date < $yearEnd)\n))\n    ].locations[]) | order(@ asc),\n    "dates": array::unique(*[_type == "project" && defined(slug.current)\n      && ($program == "" || program->slug.current == $program)\n      && ($place == "" || $place in locations)\n    ].date) | order(@ desc)\n  }': GetProjectFacetsQueryResult;
    '*[_type == "event" && slug.current == $slug][0]{\n      ...,\n      "program": program->{\n        _id, title, slug, shortLabel, displayTitle, accentColor\n      },\n      featuredArtists[]{\n        _key,\n        artist->{ _id, name, slug },\n        "image": coalesce(image, artist->image),\n        "name": coalesce(name, artist->name),\n        "bio": coalesce(bio, artist->bio)\n      }\n    }': GetEventBySlugQueryResult;
  }
}
